from enum import StrEnum


class VerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    EXPIRED = "EXPIRED"


class ClaimCategory(StrEnum):
    SKILL = "SKILL"
    EXPERIENCE = "EXPERIENCE"
    EDUCATION = "EDUCATION"
    CERTIFICATION = "CERTIFICATION"
    PROJECT = "PROJECT"
    INTERNSHIP = "INTERNSHIP"
    ACHIEVEMENT = "ACHIEVEMENT"
    OTHER = "OTHER"


class JobStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class AnalysisState(StrEnum):
    PENDING = "PENDING"
    ANALYZED = "ANALYZED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    FAILED = "FAILED"


class CompatibilityStatus(StrEnum):
    PENDING = "PENDING"
    MATCHED = "MATCHED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class FactClassification(StrEnum):
    FACT = "FACT"
    INFERENCE = "INFERENCE"
    UNKNOWN = "UNKNOWN"


class EvidenceRelationship(StrEnum):
    EXACT = "EXACT"
    RELATED = "RELATED"


class ReviewStatus(StrEnum):
    DRAFT = "DRAFT"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ApplicationStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    QUALIFIED = "QUALIFIED"
    PROPOSAL_DRAFT = "PROPOSAL_DRAFT"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    SUBMITTED = "SUBMITTED"
    CLIENT_VIEWED = "CLIENT_VIEWED"
    CLIENT_REPLIED = "CLIENT_REPLIED"
    INTERVIEW = "INTERVIEW"
    OFFER = "OFFER"
    CONTRACT = "CONTRACT"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
