from enum import StrEnum


class VerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    EXPIRED = "EXPIRED"


class ReviewStatus(StrEnum):
    DRAFT = "DRAFT"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ApplicationStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    QUALIFIED = "QUALIFIED"
    PROPOSAL_DRAFT = "PROPOSAL_DRAFT"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    SUBMITTED = "SUBMITTED"
    CLIENT_VIEWED = "CLIENT_VIEWED"
    CLIENT_REPLIED = "CLIENT_REPLIED"
    INTERVIEW = "INTERVIEW"
    OFFER = "OFFER"
    CONTRACT = "CONTRACT"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
