"""phase 3 client intelligence and evidence

Revision ID: c1e0b5296b18
Revises: 858c51dd8483
Create Date: 2026-09-21 15:55:15.031171
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c1e0b5296b18"
down_revision: str | Sequence[str] | None = "858c51dd8483"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_analyses",
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("verified_facts", sa.JSON(), nullable=False),
        sa.Column("inferences", sa.JSON(), nullable=False),
        sa.Column("unknowns", sa.JSON(), nullable=False),
        sa.Column("project_goals", sa.JSON(), nullable=False),
        sa.Column("requirements", sa.JSON(), nullable=False),
        sa.Column("concerns", sa.JSON(), nullable=False),
        sa.Column("questions", sa.JSON(), nullable=False),
        sa.Column("communication_style_indicators", sa.JSON(), nullable=False),
        sa.Column("model_used", sa.String(length=120), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "job_id", name="uq_client_analyses_client_job"),
    )
    op.create_index(
        op.f("ix_client_analyses_client_id"), "client_analyses", ["client_id"], unique=False
    )
    op.create_index(op.f("ix_client_analyses_job_id"), "client_analyses", ["job_id"], unique=False)
    op.create_table(
        "client_facts",
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("client_source_id", sa.String(length=36), nullable=True),
        sa.Column("fact", sa.Text(), nullable=False),
        sa.Column("fact_type", sa.String(length=80), nullable=False),
        sa.Column("classification", sa.String(length=24), nullable=False),
        sa.Column("verification_status", sa.String(length=24), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["client_source_id"], ["client_sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_facts_classification"), "client_facts", ["classification"], unique=False
    )
    op.create_index(op.f("ix_client_facts_client_id"), "client_facts", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_client_facts_client_source_id"), "client_facts", ["client_source_id"], unique=False
    )
    op.create_index(op.f("ix_client_facts_fact_type"), "client_facts", ["fact_type"], unique=False)
    op.create_index(
        op.f("ix_client_facts_verification_status"),
        "client_facts",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "portfolio_selections",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("ranked_projects", sa.JSON(), nullable=False),
        sa.Column("formula_version", sa.String(length=40), nullable=False),
        sa.Column("model_used", sa.String(length=120), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "user_id", name="uq_portfolio_selections_job_user"),
    )
    op.create_index(
        op.f("ix_portfolio_selections_job_id"), "portfolio_selections", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_portfolio_selections_user_id"), "portfolio_selections", ["user_id"], unique=False
    )
    op.create_table(
        "evidence_links",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("requirement_id", sa.String(length=36), nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column("portfolio_project_id", sa.String(length=36), nullable=True),
        sa.Column("relationship", sa.String(length=24), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("proposal_ready", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["verified_claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["portfolio_project_id"], ["portfolio_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["requirement_id"], ["job_requirements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "job_id",
            "requirement_id",
            "skill_id",
            "claim_id",
            "portfolio_project_id",
            name="uq_evidence_links_chain",
        ),
    )
    op.create_index(
        op.f("ix_evidence_links_claim_id"), "evidence_links", ["claim_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_links_job_id"), "evidence_links", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_evidence_links_portfolio_project_id"),
        "evidence_links",
        ["portfolio_project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_links_proposal_ready"), "evidence_links", ["proposal_ready"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_links_relationship"), "evidence_links", ["relationship"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_links_requirement_id"), "evidence_links", ["requirement_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_links_skill_id"), "evidence_links", ["skill_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_links_user_id"), "evidence_links", ["user_id"], unique=False)
    op.add_column("clients", sa.Column("company", sa.String(length=240), nullable=True))
    op.add_column("clients", sa.Column("website", sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "website")
    op.drop_column("clients", "company")
    op.drop_index(op.f("ix_evidence_links_user_id"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_skill_id"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_requirement_id"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_relationship"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_proposal_ready"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_portfolio_project_id"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_job_id"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_claim_id"), table_name="evidence_links")
    op.drop_table("evidence_links")
    op.drop_index(op.f("ix_portfolio_selections_user_id"), table_name="portfolio_selections")
    op.drop_index(op.f("ix_portfolio_selections_job_id"), table_name="portfolio_selections")
    op.drop_table("portfolio_selections")
    op.drop_index(op.f("ix_client_facts_verification_status"), table_name="client_facts")
    op.drop_index(op.f("ix_client_facts_fact_type"), table_name="client_facts")
    op.drop_index(op.f("ix_client_facts_client_source_id"), table_name="client_facts")
    op.drop_index(op.f("ix_client_facts_client_id"), table_name="client_facts")
    op.drop_index(op.f("ix_client_facts_classification"), table_name="client_facts")
    op.drop_table("client_facts")
    op.drop_index(op.f("ix_client_analyses_job_id"), table_name="client_analyses")
    op.drop_index(op.f("ix_client_analyses_client_id"), table_name="client_analyses")
    op.drop_table("client_analyses")
    # ### end Alembic commands ###
